credentials-file: /etc/cloudflared/credentials.json

ingress:
  - hostname: portainer.purrbrews.cc
    service: http://192.168.0.10:9000
  - hostname: pihole.purrbrews.cc
    service: http://192.168.0.11:80
  - service: http_status:404